# Generated by Django 5.1.3 on 2025-05-16 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aichatsession_airequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airequest',
            old_name='message',
            new_name='messages',
        ),
    ]
